common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from common import views

app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from hdrb.views import base_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hdrb/', include('hdrb.urls')),
    path('',base_views.index, name='index'),
    path('common/',include('common.urls')),
]

hdrb/urls.py
from django.contrib import admin
from django.urls import path
from hdrb.views import base_views, reservation_views

app_name = 'hdrb'
urlpatterns = [
    path('', base_views.index, name='index'),
    path('reservation/create/', reservation_views.reservation_create, name='reservation_create'),
]

common/models.py
from django.db import models

# Create your models here.

hdrb/models.py
from django.contrib.auth.models import User
from django.db import models
from django import forms
from django.utils import timezone
from .validators import validate_start_time, validate_end_time


class Reservation(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    start_time = models.DateTimeField(validators=[validate_start_time])
    end_time = models.DateTimeField(validators=[validate_end_time])
    num_of_people = models.IntegerField()
    allow_join = models.BooleanField()
    memo = models.TextField(null=True, blank=True)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    real_name = forms.CharField(label='이름')
    class Meta:
        model = User
        fields = ("username","password1","password2","real_name")

hdrb/forms.py
from django import forms
from django.db.models import Q
from hdrb.models import Reservation


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['start_time', 'end_time', 'num_of_people', 'allow_join', 'memo']
        labels = {
            'start_time': '시작 시간',
            'end_time': '종료 시간',
            'num_of_people': '인원수',
            'allow_join': '합석 가능',
            'memo': 'MEMO',
        }

    def clean(self):
        start_time = self.cleaned_data.get('start_time')
        end_time = self.cleaned_data.get('end_time')
        allow_join = self.cleaned_data.get('allow_join')
        if start_time is not None and end_time is not None and allow_join is not None:
            reservation_list = Reservation.objects.all()
            reservation_set = Reservation.objects.filter(
                (Q(start_time__lte=start_time) & Q(end_time__gt=start_time))
                | (Q(start_time__lte=end_time) & Q(end_time__gt=end_time))
            )
            if end_time.__lt__(start_time):
                raise forms.ValidationError('예약 종료 시간은 시작 시간 이후여야 합니다.')

            if reservation_set and (not allow_join or not reservation_set.first().allow_join):
                raise forms.ValidationError("기존 예약과 충돌합니다.")
        return self.cleaned_data

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

# Create your views here.
from .forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

hdrb/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def index(request):
    return HttpResponse('hello hdrb')

hdrb/views/base_views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'hdrb/temp.html')

hdrb/views/reservation_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from hdrb.forms import ReservationForm


@login_required()
def reservation_create(request):
    """
    예약 정보 생성
    """
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.writer = request.user
            reservation.save()
            return redirect('hdrb:index')
    else:
        form = ReservationForm()
    context = {'form': form}
    return render(request, 'hdrb/reservation_form.html', context)

hdrb/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {#    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">     #}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'reset.css' %}">
    <title>해다락방</title>
</head>
<body>
{% include 'navbar.html' %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

hdrb/templates/common/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="login_container">
        <div class="login_header">
            <h1>로그인</h1>
            <div class="signup_link">
                <span>또는 </span><a href="{% url 'common:signup' %}">회원가입</a>
            </div>
        </div>
        <div class="login_block">
            <form method="post" action="{% url 'common:login' %}">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}">
                {% include 'form_errors.html' %}
                <div class="id_block">
                    <label for="username" class="hide">ID</label>
                    <input type="text" name="username" id="username" placeholder="아이디"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="pw_block">
                    <label for="password" class="hide">비밀번호</label>
                    <input type="password" name="password" id="password" placeholder="비밀번호"
                           value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="submit_btn">로그인</button>
            </form>
        </div>
    </div>

{% endblock %}

hdrb/templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
    <div class="signup_container">
        <div class="signup_header">
            <h1>회원가입</h1>
            <div class="login_link">
                <span>또는 </span><a href="{% url 'common:login' %}">로그인</a>
            </div>
        </div>
        <div class="signup_block">
            <form method="post" action="{% url 'common:signup' %}">
                {% csrf_token %}
                {% include 'form_errors.html' %}
                <div class="id_block">
                    <label for="username" class="hide">ID</label>
                    <input type="text" id="username" name="username"
                           placeholder="아이디"
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="pw1_block">
                    <label for="password1" class="hide">비밀번호</label>
                    <input type="password" id="password1" name="password1"
                           placeholder="비밀번호"
                           value="{{ form.password1.value|default_if_none:'' }}">
                </div>
                <div class="pw2_block">
                    <label for="password2" class="hide">비밀번호 확인</label>
                    <input type="password" id="password2" name="password2"
                           placeholder="비밀번호 확인"
                           value="{{ form.password2.value|default_if_none:'' }}">
                </div>
                <div class="real_name_block">
                    <label for="real_name" class="hide">이름</label>
                    <input type="text" id="real_name" name="real_name"
                           placeholder="이름 (실명)"
                           value="{{ form.real_name.value|default_if_none:'' }}">
                </div>
                <button type="submit" class="submit_btn">가입하기</button>
            </form>
        </div>
    </div>
{% endblock %}

hdrb/templates/form_errors.html
{% if form.errors %}
    <div id="error_container">
        {% for field in form %}
            {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                <div class="error_box">
                    <div class="error_field">
                        {{ field.label }}
                    </div>
                    <div class="error_contents">
                        - {{ error }}
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
            <div class="error_box error_contents">
                - {{ error }}
            </div>
        {% endfor %}
    </div>
{% endif %}

hdrb/templates/hdrb/reservation_form.html
{% extends 'base.html' %}
{% block content %}
    <div id="create_form">
        <div class="main_container">
            <h1>예약하기</h1>
            <div class="inner">
                <form method="post">
                    {% csrf_token %}
                    {% include 'form_errors.html' %}
                    <div class="box timer">
                        <div class="start_time_field">
                            <label for="start_time" class="sub_title_style">시작 시간</label>
                            <input type="datetime-local" name="start_time" id="start_time"
                                   value="{{ form.start_time.value }}">
                        </div>
                        <div class="end_time_field">
                            <label for="end_time" class="sub_title_style">종료 시간</label>
                            <input type="datetime-local" name="end_time" id="end_time"
                                   value="{{ form.end_time.value }}">
                        </div>
                    </div>
                    <div class="box people_field">
                        <label for="num_of_people" class="sub_title_style">인원수</label>
                        <input type="number" name="num_of_people" id="num_of_people" min="1" max="10"
                               value="{{ form.num_of_people.value|default_if_none:'1' }}">
                    </div>
                    <div class="box join_field">
                        <span class="sub_title_style">합석 가능해요</span>
                        <input type="checkbox" name="allow_join" id="checkbox" {% if form.allow_join.value %}
                               checked {% endif %} >
                        <label for="checkbox"></label>
                        {#                        <label for="allow_join"><span class="sub_title_style">합석 가능해요</span></label>#}
                    </div>
                    <div class="box memo_field">
                        <label for="memo" class="sub_title_style">MEMO</label>
                        <textarea rows="4" name="memo" id="memo"
                                  placeholder="내용을 입력하세요">{{ form.memo.value|default_if_none:'' }}</textarea>
                    </div>
                    <div class="button_field">
                        <button type="submit"> 저장</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

hdrb/templates/hdrb/temp.html
{% extends 'base.html' %}
{% block content %}
    <form>
        <a  {% if user.is_authenticated %}
            href="{% url "hdrb:reservation_create" %}"
        {% else %}
            href="#"
        {% endif %}>예약하기</a>
    </form>
{% endblock %}

hdrb/templates/navbar.html
<div>
    <a href="{% url 'hdrb:index' %}">해다락방</a>
    {% if user.is_authenticated %}
        <a href="{% url 'common:logout' %}">{{ user.username }} (로그아웃) </a>
    {% else %}
        <a href="{% url 'common:login' %}">로그인</a>
    {% endif %}
</div>